### ISSUE TITLE
binocle/test/TestGps.java is 404 here on github

### ISSUE THREAD

**Issue by supaplextor** [Genymobile/genymotion-binocle#5] opened 2016-08-22 17:02 UTC
https://github.com/Genymobile/genymotion-binocle
https://github.com/Genymobile/genymotion-binocle/blob/master/binocle/src/instrumentTest/java/com/genymotion/binocle/test/TestGps.java

**Comment by eyal-lezmy** [comment] 2016-08-22 22:29
Hi,

Where did you find this link? 
The good one is now this: https://github.com/Genymobile/genymotion-binocle/blob/master/binocle/src/androidTest/java/com/genymotion/binocle/test/TestGps.java

**Comment by supaplextor** [comment] 2016-08-23 03:26
I think it's probably from the README.md (I'm green to markdown).  Search for TestGps.java on this page: https://github.com/Genymobile/genymotion-binocle

**Comment by eyal-lezmy** [comment] 2016-08-24 21:14
@supaplextor thanks a lot for highlighting this. All the links have been fixed on the doc.
I close the issue as the problem is now solved.

Cheers
Eyal

**Closed by eyal-lezmy** 2016-08-24 21:14 UTC
